"""Database creation

Revision ID: 3e77f86d34e6
Revises: f184fb00be5c
Create Date: 2023-03-07 21:47:48.562466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e77f86d34e6'
down_revision = 'f184fb00be5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
