"""relationship for userr

Revision ID: 581e6ef855e1
Revises: c179ec36ded2
Create Date: 2023-03-13 14:28:11.987096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581e6ef855e1'
down_revision = 'c179ec36ded2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
