"""relationship for user

Revision ID: c179ec36ded2
Revises: 01fbb13142da
Create Date: 2023-03-13 14:16:13.018076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c179ec36ded2'
down_revision = '01fbb13142da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
